# formats the input text. If font s not specified uses the default one.
# A random font can be generated by calling art_print(text, 'random')

import pyfiglet
import random

fonts = pyfiglet.FigletFont.getFonts()
n = random.randrange(len(fonts))


def art_print(text, usr_font='default'):

    if usr_font in fonts:
        art_text = pyfiglet.figlet_format(text, font=usr_font)
    elif usr_font == 'random':
        usr_font = fonts[n]
        art_text = pyfiglet.figlet_format(text, font=usr_font)
    else:
        art_text = pyfiglet.figlet_format(text)

    print(art_text)
